services:
  db:
    container_name: recipes-app-database
    image: postgres:18
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/18/data
    volumes:
      - pgdata:/var/lib/postgresql/18/data
    ports:
      - "5432:5432"
volumes:
  pgdata:
